import os
from datetime import date, timedelta

from fastapi import APIRouter, Depends, HTTPException, Security, status
from fastapi.security.api_key import APIKeyHeader
from pydantic import BaseModel
from sqlalchemy.orm import Session
from sqlalchemy import select

from app.core.database import get_db
from app.models.appointment import Appointment, AppointmentStatus
from app.core.encryption import hash_phone

router = APIRouter(prefix="/appointments", tags=["Appointments"])

# How far ahead we look for a patient's upcoming appointment.
# Must match the filing clerk's 3-day window so the record is
# already "confirmed" and visible to staff when the patient confirms.
CONFIRM_WINDOW_DAYS = 3

# ── Bot-to-backend shared secret ──────────────────────────────────────────────
# These endpoints are internal — called only by patient_bot.py, never by the
# browser frontend. A shared secret in the X-Bot-Secret header prevents
# arbitrary callers from cancelling or confirming appointments by phone number.
_BOT_SECRET = os.getenv("BOT_SECRET")
_bot_secret_header = APIKeyHeader(name="X-Bot-Secret", auto_error=False)


def _verify_bot_secret(key: str = Security(_bot_secret_header)):
    """Dependency: rejects requests that don't carry the correct bot secret."""
    if not _BOT_SECRET:
        # If no secret is configured (e.g. local dev without ...env), allow through
        # but log a warning so developers notice.
        return
    if key != _BOT_SECRET:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Invalid or missing bot secret.",
        )


# ── Request bodies ─────────────────────────────────────────────────────────────

class ConfirmPayload(BaseModel):
    phone_number: str          # E.164, e.g. "+27821234567"
    express_code: str          # Generated by the bot, e.g. "INS-A3K7"
    distribution_channel: str  # "WhatsApp" or "SMS"


class OptOutPayload(BaseModel):
    phone_number: str          # E.164


# ── Helpers ───────────────────────────────────────────────────────────────────

def _find_upcoming_appointment(phone_number: str, db: Session) -> Appointment | None:
    """
    Returns the earliest upcoming confirmed appointment for this phone number
    within the 3-day confirmation window, or None if none exists.

    Lookup uses phone_number_hash (HMAC-SHA256) rather than plaintext --
    the encrypted phone_number column can't be used in a WHERE clause because
    Fernet produces different ciphertext on every encrypt call.
    """
    today = date.today()
    cutoff = today + timedelta(days=CONFIRM_WINDOW_DAYS)

    stmt = (
        select(Appointment)
        .where(
            Appointment.phone_number_hash == hash_phone(phone_number),
            Appointment.status == AppointmentStatus.confirmed,
            Appointment.collection_date >= today,
            Appointment.collection_date <= cutoff,
        )
        .order_by(Appointment.collection_date)
        .limit(1)
    )
    return db.execute(stmt).scalar_one_or_none()


# ── PATCH /appointments/confirm ───────────────────────────────────────────────

@router.patch(
    "/confirm",
    summary="Patient confirmed slot via WhatsApp/SMS",
    description=(
        "Called by the patient bot when a patient replies '1'. "
        "Stores the express code and channel on their appointment record. "
        "Returns 404 if no upcoming confirmed appointment is found for this number — "
        "the bot uses this to send the patient a 'no appointment found' reply."
    ),
)
def confirm_appointment(payload: ConfirmPayload, db: Session = Depends(get_db), _: None = Depends(_verify_bot_secret)):
    """
    Status stays 'confirmed' — this enriches the record, it does not advance
    the workflow. The filing clerk still needs to physically pull the file.

    What changes:
        appointment.express_code         = "INS-A3K7"
        appointment.distribution_channel = "WhatsApp"
    """
    appt = _find_upcoming_appointment(payload.phone_number, db)

    if not appt:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="No upcoming confirmed appointment found for this number.",
        )

    appt.express_code = payload.express_code
    appt.distribution_channel = payload.distribution_channel
    db.commit()
    db.refresh(appt)

    return {
        "status":       "confirmed",
        "id":           appt.id,
        "express_code": appt.express_code,
        "collection_date": str(appt.collection_date),
        "time_slot":    appt.time_slot,
    }


# ── PATCH /appointments/opt-out ───────────────────────────────────────────────

@router.patch(
    "/opt-out",
    summary="Patient cancelled/rescheduled via WhatsApp/SMS",
    description=(
        "Called by the patient bot when a patient replies '2'. "
        "Transitions the appointment to 'cancelled', removing it from the "
        "filing clerk's queue. Returns 404 if no upcoming appointment is found."
    ),
)
def opt_out_appointment(payload: OptOutPayload, db: Session = Depends(get_db), _: None = Depends(_verify_bot_secret)):
    """
    Status transition: confirmed → cancelled.

    Effect on the rest of the system:
      - Filing clerk's /filing/upcoming feed: record disappears
        (EXCLUDED_STATUSES already contains 'cancelled' — double-check filing.py).
      - Pharmacy queues: unaffected (record never reached 'pulled').
    """
    appt = _find_upcoming_appointment(payload.phone_number, db)

    if not appt:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="No upcoming confirmed appointment found for this number.",
        )

    appt.status = AppointmentStatus.cancelled
    db.commit()

    return {
        "status": "cancelled",
        "id":     appt.id,
    }